version: "2.1"

services:
  webapp:
    image: python:alpine
    build:
      context: $PWD
      dockerfile: $PWD/etc/compose/Dockerfile
    environment:
      - DJANGO_SECRET=local
      - DEBUG=True
      - SKIP_TASK_QUEUE=False
      - REHIVE_API_URL=https://rehive.com/api/3/
      - GCLOUD_USE_STATIC=False
    restart: always
    ports:
      - 8000:8000
    networks:
      - main
    depends_on:
      - postgres
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"

  postgres:
    image: postgres:9.6
    ports:
      - '5111:5432'
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      main:
        aliases:
          - postgres

  management:
    image: python:alpine

volumes:
  pgdata:

networks:
  main:
