version: "2.1"

services:
  webapp:
    image: python:alpine
    build:
      context: $PWD
      dockerfile: $PWD/${DOCKER_FILE}
    env_file: $PWD/.env
    restart: always
    command: /bin/sh -c "gunicorn config.wsgi:application --bind 0.0.0.0:${WEBAPP_PORT} --config file:config/gunicorn.py"
    ports:
      - ${WEBAPP_PORT}:${WEBAPP_PORT}
    networks:
      - main
    depends_on:
      - postgres
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"

  postgres:
    image: postgres:9.6
    ports:
      - '${LOCAL_POSTGRES_PORT}:5432'
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      main:
        aliases:
          - postgres

  management:
    image: python:alpine

volumes:
  pgdata:

networks:
  main:
